In [4]:
import torch

x: torch.Tensor = torch.tensor(3.0) # tensor 代表张量，一个元素的一阶张量 也叫做标量（scalar）
y: torch.Tensor = torch.tensor(2.0)
print(x.type())
print(y.type())
x + y, x * y, x / y, x**y

torch.FloatTensor
torch.FloatTensor


(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [5]:
# 向量
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [6]:
# 通过索引访问向量的任一元素
x[3]

tensor(3)

In [7]:
# 向量的长度
len(x)

4

In [8]:
# 向量的形状，也就是长度
x.shape

torch.Size([4])

In [10]:
# 矩阵，也就是二维向量
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [11]:
# 矩阵转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [12]:
# 对称矩阵
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [14]:
# 因为B是对称矩阵，所以B的转置矩阵等于它本身
B ==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [15]:
# 三阶段张量
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [16]:
#张量的算术
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [17]:
#张量乘法
A * B


tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [18]:
# 张量的加减乘除不会改变张量的形状
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [19]:
# 降维
x = torch.arange(4, dtype=torch.float32) # 不指定形状（shape）就是一维张量（向量）
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [20]:
# 任意维度的张量都可以求和
A.shape, A.sum()


(torch.Size([5, 4]), tensor(190.))

In [32]:
A_sum_axis0 = A.sum(axis=0) # 列求和
A,A_sum_axis0, A_sum_axis0.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([40., 45., 50., 55.]),
 torch.Size([4]))

In [31]:
A_sum_axis1 = A.sum(axis=1) # 行求和
A,A_sum_axis1, A_sum_axis1.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([ 6., 22., 38., 54., 70.]),
 torch.Size([5]))

In [33]:
# 2.3.7. 点积（Dot Product）¶
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [35]:
A,A.shape, x.shape, torch.mv(A, x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

In [36]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [37]:
torch.norm(torch.ones((4, 9)))

tensor(6.)